#Section 01. 넘파이 소개
## 1. 넘파이 개념

In [ ]:
# 주피터 노트북 사용자
!pip install numpy

In [1]:
import numpy as np # numpy의 별칭을 np로 설정
print(np.__version__) # 파이썬 라이브러리의 버전 확인

1.25.2


In [8]:
# 리스트로 2차원 배열 구현하기
list_1 = []
temp = []
for i in range(0,12):
  temp.append(i)
  if i == 3 or i == 7 or i== 11:
    list_1.append(temp)
    temp = []
list_1

[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]

##2. 넘파이 배열

In [24]:
np.arange(12).reshape(2, 2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [25]:
d=np.arange(12).reshape(3,4)
print(d,d.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (3, 4)


###dtype

In [21]:
# ndarray (n-차원 배열) n-dimension array
type(d)

numpy.ndarray

In [ ]:
print(d.dtype)

int32


###ndim

In [ ]:
print(d.ndim)

2


리스트    vs    넘파이
- 속도가 느림         ,빠름
- 쉽표로 요소 구분    ,공백으로 구분
- 서로다른 데이터형   ,데이터형 통일

###T

In [26]:
print(d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
print(d.T) # 전치 행렬

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


###size

In [ ]:
print(d.size) # 요소의 개수

12


###nbtypes : 배열의 바이트 표현

In [ ]:
print(d.nbytes) # 64bit는 8byte이므로 총 96byte(8*12)

48


### flat : 배열 요소의 값을 초기화

In [27]:
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
d.flat=1
print(d)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


##3. 넘파이 배열 생성
##리스트로 생성

In [ ]:
mynpa1=np.array([1, 2, 3])
print(type(mynpa1))

<class 'numpy.ndarray'>


In [ ]:
mylist2=[[1, 2, 3],
 [4, 5, 6]]
print(type(mylist2))
mynpa2=np.array(mylist2) # 변수명 직접 입력
print(type(mynpa2))

<class 'list'>
<class 'numpy.ndarray'>


In [35]:
# 넘파이 배열만들기 : 0부터 15까지의 값을 가지는 넘파이 1차원 배열 ( 15,)
test_num = np.arange(15)
print(test_num)
# reshape : 3 , 5 형태로 변경
test_num = test_num.reshape(3, 5)
print(test_num)
# ndim : 차수확인
print(test_num.ndim)
# size : 요소의 개수가 몇개인지
print(test_num.size)
# dtype : 넘파이를 구성하는 데이터의 타입
print(test_num.dtype)
# 초기화 0으로
test_num.flat=0
print(test_num)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
2
15
int64
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


###데이터프레임으로 생성

In [46]:
import pandas as pd
mypd1=pd.DataFrame(
    {
        'A': [1, 2, 3],
        'B': [4, 5, 6]
    }
)
print(type(mypd1))
mynp1=np.array(mypd1)
print(type(mynp1))
print(mynp1)
mypd1

<class 'pandas.core.frame.DataFrame'>
<class 'numpy.ndarray'>
[[1 4]
 [2 5]
 [3 6]]


A  B
0  1  4
1  2  5
2  3  6

In [47]:
mylist2=[[1, 2, 3],
 [4, 5, 6]]
print(type(mylist2))
mypd2=pd.DataFrame(mylist2)
print(type(mypd2))
mynpa2=np.array(mypd2)
print(type(mynpa2))
mypd2

<class 'list'>
<class 'pandas.core.frame.DataFrame'>
<class 'numpy.ndarray'>


0  1  2
0  1  2  3
1  4  5  6

##4. n차원 넘파이 배열
##5. 1차원 넘파이 배열 생성


In [48]:
import numpy as np
a=np.arange(3)
print(a, type(a), a.ndim, a.shape)

[0 1 2] <class 'numpy.ndarray'> 1 (3,)


####① 종료값만 설정

In [49]:
a2=np.arange(4)
a2

array([0, 1, 2, 3])

#### ② 시작값, 종료값 설정

In [50]:
a2=np.arange(2, 4)
print(a2, a2.shape)

[2 3] (2,)


####③ 시작값, 종료값, 증가값 모두 설정

In [ ]:
a3=np.arange(0, 5, 2)
print(a3, a3.shape)

[0 2 4] (3,)


In [61]:
# 연습
# 적당한 리스트 -> 데이터프레임 ->넘파이배열
from random import randint
list_1 = [ randint(0,100) for i in range(12)]
print(list_1, type(list_1))
df = pd.DataFrame(list_1)
# print(df, type(df))
# df
arr = np.array(df).reshape(3,4)
print(arr, type(arr), arr.ndim, arr.shape)
arr.flat = 0
print(arr)

[21, 56, 18, 39, 4, 30, 5, 11, 9, 99, 9, 39] <class 'list'>
[[21 56 18 39]
 [ 4 30  5 11]
 [ 9 99  9 39]] <class 'numpy.ndarray'> 2 (3, 4)
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


##6. 2차원 넘파이 배열 생성
### 2행 3열의 배열 생성

In [62]:
m=np.arange(6).reshape(2, 3)
print(m, m.shape)

[[0 1 2]
 [3 4 5]] (2, 3)


In [ ]:
m=np.array([np.arange(3), np.arange(3, 6)])
print(m, m.shape)

[[0 1 2]
 [3 4 5]] (2, 3)


In [63]:
np.arange(6).reshape(3, 2)

array([[0, 1],
       [2, 3],
       [4, 5]])

###3행 2열의 배열 생성

In [64]:
m=np.array([[0, 3],
 [1, 4],
 [2, 5]])
print(m, m.shape)
print(m.shape[0], m.shape[1])

[[0 3]
 [1 4]
 [2 5]] (3, 2)
3 2


In [66]:
m=np.array([np.arange(0, 4, 3), np.arange(1, 5, 3),
np.arange(2, 6, 3)])
print(m, m.shape)

[[0 3]
 [1 4]
 [2 5]] (3, 2)


##7. 3차원 넘파이 배열 생성

In [ ]:
m=np.array([[[0, 1, 2],
 [3, 4, 5]],
 [[0, 1, 2],
 [3, 4, 5]]])
print(m)
print(m.shape)

[[[0 1 2]
  [3 4 5]]

 [[0 1 2]
  [3 4 5]]]
(2, 2, 3)


In [ ]:
m=np.array([[[0, 1],
 [2, 3]],
 [[4, 5],
 [6, 7]],
 [[8, 9],
 [10, 11]]])
print(m, m.shape)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]] (3, 2, 2)


In [ ]:
m=np.array([[[0, 1, 2]],
 [[3, 4, 5]],
 [[0, 1, 2]],
 [[3, 4, 5]]])
print(m, m.shape)

[[[0 1 2]]

 [[3 4 5]]

 [[0 1 2]]

 [[3 4 5]]] (4, 1, 3)


###<여기서 잠깐> 파이썬의 range 함수와 넘파이의 arange 함수

In [ ]:
list=[1, 2, 3, 4, 5]
for i in list:
  print(i)

1
2
3
4
5


In [ ]:
list=[1, 2, 3, 4, 5]
for i in range(1, 6):
  print(i)

1
2
3
4
5


In [ ]:
list=[1, 2, 3, 4, 5]
for i in range(1, 6, 2):
  print(i)

1
3
5


In [ ]:
arr=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
arr

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
arr=np.arange(start=1, stop=11, step=1)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr=np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr=np.arange(start=1, stop=10, step=2)
arr

array([1, 3, 5, 7, 9])

In [ ]:
arr=np.arange(1, 10, 2)
arr

array([1, 3, 5, 7, 9])

# Section 02. 배열 다루기
## 1. 배열의 데이터형 확인과 변형

In [ ]:
import numpy as np

nda=np.array([0, 1, 2, 3, 4, 5])
print(nda, type(nda)) # nda 변수의 데이터형 반환
print(nda.dtype) # 넘파이 배열인 nda 요소의 자료형 반환
nda # 넘파이 배열이므로 array([]) 형식으로 표시

[0 1 2 3 4 5] <class 'numpy.ndarray'>
int32


array([0, 1, 2, 3, 4, 5])

In [ ]:
nda1=np.array([0, 1, 2, 3.0, 4, 5])
print(nda1, nda1.dtype)

[0. 1. 2. 3. 4. 5.] float64


In [ ]:
nda2=np.array([0, 1, 2, 3, 4, 5])
print(nda2, nda2.dtype)

[0 1 2 3 4 5] int32


## 2. 배열의 형태 변경
###배열의 구조 변경하기: reshape 함수

In [ ]:
m1=np.arange(6)
print(m1)
print(m1.shape)

[0 1 2 3 4 5]
(6,)


In [ ]:
m2=m1.reshape(6, 1)
print(m2, m2.shape) # 1행 6열을 6행 1열로 변경

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]] (6, 1)


In [ ]:
m2=m1.reshape(2, 3)
print(m2, m2.shape)

[[0 1 2]
 [3 4 5]] (2, 3)


In [ ]:
m1=np.arange(12)
m3=m1.reshape(2, 2, 3)
print(m3, m3.shape)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]] (2, 2, 3)


In [ ]:
# -1의 역활은.. 자동 계산
m1=np.arange(6)
print(m1, m1.shape)
m2=m1.reshape(-1, 2) # 행 수는 자동, 2열 생성
print(m2, m2.shape)
m2=m1.reshape(-1, 3) # 행 수는 자동, 3열 생성
print(m2, m2.shape)
m2=m1.reshape(-1, 1) # 행 수는 자동, 1열 생성
print(m2, m2.shape)

[0 1 2 3 4 5] (6,)
[[0 1]
 [2 3]
 [4 5]] (3, 2)
[[0 1 2]
 [3 4 5]] (2, 3)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]] (6, 1)


In [ ]:
m1=np.arange(6)
m3=m1.reshape(-1, 2, 3)
print(m3, m3.shape)
m3=m1.reshape(-1, 3, 2) # 면 수 자동, 3행 2열 생성
print(m3,m3.shape)
m3=m1.reshape(2, 3, -1) # 열 수 자동, 2면 3행 생성
print(m3, m3.shape)

[[[0 1 2]
  [3 4 5]]] (1, 2, 3)
[[[0 1]
  [2 3]
  [4 5]]] (1, 3, 2)
[[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]] (2, 3, 1)


In [71]:
import numpy as np
arr = np.arange(12).reshape(3, 4)
arr.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

###다차원 배열을 1차원 배열로 평탄화하기: flatten 함수

In [ ]:
a=np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
f=a.flatten()
print(f, f.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11] (12,)


###배열의 방향 변경하기

In [93]:
arr = np.arange(25).reshape(5, 5)
print(arr)
list_1 = arr.tolist()
# 1을 출력
print(arr[: , 1:3])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 1  2]
 [ 6  7]
 [11 12]
 [16 17]
 [21 22]]


In [110]:
print(arr[ :: -1]) # 행 순서를 거꾸로 변경
print("*"*20)
print(arr[:, ::-1]) # 열 순서를 거꾸로 변경
print("*"*20)
print(arr[::-1, ::-1]) # 행렬 순서를 거꾸로 변경


[[20 21 22 23 24]
 [15 16 17 18 19]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]]
********************
[[ 4  3  2  1  0]
 [ 9  8  7  6  5]
 [14 13 12 11 10]
 [19 18 17 16 15]
 [24 23 22 21 20]]
********************
[[24 23 22 21 20]
 [19 18 17 16 15]
 [14 13 12 11 10]
 [ 9  8  7  6  5]
 [ 4  3  2  1  0]]


In [111]:
print(a[:,::-1]) # 열 순서를 거꾸로 변경

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]]


In [112]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [113]:
print(a[::-1,::-1]) # 행과 열 순서를 거꾸로 변경

[[11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]


In [114]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [116]:
t=a.transpose()  # 전치함수..   a.T
print(a, a.shape) # a 배열은 3행 4열
print(t, t.shape) # t 배열은 a 배열을 4행 3열로 변경한 것

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (3, 4)
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]] (4, 3)


In [117]:
print(a.T) # transpose() 함수와 결과 동일

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


##3. 배열 통합과 분할

In [127]:
a=np.arange(9).reshape(3, 3)
b=a*2
print(a)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


In [125]:
temp1 = np.arange(8).reshape(2, 4)
temp2 = np.arange(8, 16).reshape(2, 4)
print(temp1)
print('%')
print(temp2)
print('*'*20)
print(temp1 %  temp2)

[[0 1 2 3]
 [4 5 6 7]]
%
[[ 8  9 10 11]
 [12 13 14 15]]
********************
[[0 1 2 3]
 [4 5 6 7]]


In [133]:
b = a[::-1,::-1]
print(a,a.shape)
print(b,b.shape)

[[0 1 2]
 [3 4 5]
 [6 7 8]] (3, 3)
[[8 7 6]
 [5 4 3]
 [2 1 0]] (3, 3)


In [132]:
r=np.vstack((a, b))
print(r, r.shape)

[[0 1 2]
 [3 4 5]
 [6 7 8]
 [8 7 6]
 [5 4 3]
 [2 1 0]] (6, 3)


In [134]:
np.hstack((a, b)) # column_stack

array([[0, 1, 2, 8, 7, 6],
       [3, 4, 5, 5, 4, 3],
       [6, 7, 8, 2, 1, 0]])

In [136]:
c=np.row_stack((a, b))  # vstack
print(c, c.shape)

[[0 1 2]
 [3 4 5]
 [6 7 8]
 [8 7 6]
 [5 4 3]
 [2 1 0]] (6, 3)


In [139]:
x=np.concatenate((a, b), axis=0)
print(x, x.shape)

[[0 1 2]
 [3 4 5]
 [6 7 8]
 [8 7 6]
 [5 4 3]
 [2 1 0]] (6, 3)


###열 방향으로 합치기

In [140]:
r=np.hstack((a, b))
print(r, r.shape)

[[0 1 2 8 7 6]
 [3 4 5 5 4 3]
 [6 7 8 2 1 0]] (3, 6)


In [141]:
c=np.column_stack((a, b))
print(c, c.shape)

[[0 1 2 8 7 6]
 [3 4 5 5 4 3]
 [6 7 8 2 1 0]] (3, 6)


In [142]:
x=np.concatenate((a, b), axis=1)
print(x, x.shape)

[[0 1 2 8 7 6]
 [3 4 5 5 4 3]
 [6 7 8 2 1 0]] (3, 6)


###행 단위로 분할하기

In [144]:
a=np.arange(12).reshape(4, 3)
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [147]:
print(np.vsplit(a, 4))

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]]), array([[ 9, 10, 11]])]


In [ ]:
print(np.split(a, 4, axis=0))

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]]), array([[ 9, 10, 11]])]


In [ ]:
print(a[0:1], a[1:2], a[2:3], a[3:])

[[0 1 2]] [[3 4 5]] [[6 7 8]] [[ 9 10 11]]


###열 단위로 분할하기

In [ ]:
a=np.arange(12).reshape(3, 4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
print(np.hsplit(a, 4))

[array([[0],
       [4],
       [8]]), array([[1],
       [5],
       [9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


In [ ]:
print(np.split(a, 4, axis=1))

[array([[0],
       [4],
       [8]]), array([[1],
       [5],
       [9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


#Section 03. 배열의 인덱싱과 슬라이싱
##1. 1차원 배열의 인덱싱과 슬라이싱

In [ ]:
d=np.arange(6)
print(d, d.shape)

[0 1 2 3 4 5] (6,)


In [ ]:
# 1차원 배열의 인덱싱
print(d[0], d[1], d[2], d[-1], d[-2])

0 1 2 5 4


In [ ]:
# 1차원 배열의 슬라이싱
print(d[2:3], d[:], d[:-1])
print(d[::2], d[::-1])
d[0]=10 # 요소 값 변경
print(d)

[2] [0 1 2 3 4 5] [0 1 2 3 4]
[0 2 4] [5 4 3 2 1 0]
[10  1  2  3  4  5]


##2. 2차원 배열의 인덱싱과 슬라이싱


In [ ]:
d=np.arange(12).reshape(3, 4)
print(d, d.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (3, 4)


In [ ]:
# 2차원 배열의 인덱싱
print(d[0][0]) # 배열명[행][열] 형태
print(d[0,0]) # 배열명[행,열] 형태
print(d[2,1])

0
0
9


In [ ]:
# 2차원 배열의 슬라이싱
print(d[0]) # 0행만 슬라이싱
print(d[0,:]) # 0행의 전체 열 슬라이싱
print(d[:,:-1]) # 마지막 열 제외한 전체 행과 열 슬라이싱
print(d[::2,::2]) # 2행 2열 간격으로 전체 행과 열 슬라이싱

[0 1 2 3]
[0 1 2 3]
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]
[[ 0  2]
 [ 8 10]]


In [ ]:
d[0]=20 # 0번 행 요소를 모두 20으로 변경
print(d)

[[20 20 20 20]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
d[::2,::3]=30 # 슬라이싱된 요소값을 한꺼번에 변경
print(d[::2,::3])
print(d)

[[30 30]
 [30 30]]
[[30 20 20 30]
 [ 4  5  6  7]
 [30  9 10 30]]


In [ ]:
d[:,:]=-1 # 전체 요소값을 한꺼번에 변경
print(d)

[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]


##3. 3차원 배열의 인덱싱과 슬라이싱

In [ ]:
d=np.arange(12).reshape(2, 2, 3)
print(d, d.shape)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]] (2, 2, 3)


In [ ]:
# 3차원 배열의 인덱싱
print(d[0][0][0]) # 0면 0행 0열 인덱싱
print(d[0, 0, 0]) # 0면 0행 0열 인덱싱
print(d[0, 1, 2]) # 0면 1행 2열 인덱싱

0
0
5


In [ ]:
# 3차원 배열의 슬라이싱
print(d[:,:-1,:-1])

[[[0 1]]

 [[6 7]]]


In [ ]:
print(d[:,1:,1:])

[[[ 4  5]]

 [[10 11]]]


In [ ]:
print(d[:,:,-1])

[[ 2  5]
 [ 8 11]]


In [ ]:
print(d[:,-1,-1])
print(d[-1,-1,-1])

[ 5 11]
11


In [ ]:
a=np.arange(12)
print(a, a.shape)
print(a[0]) # 스칼라
print(a[0:1]) # 배열(ndarray)

[ 0  1  2  3  4  5  6  7  8  9 10 11] (12,)
0
[0]


In [ ]:
# 연습
# ndarray  reshape, 합치기, 전치, 슬라이싱
# 1. (4,3) ndarray 생성 a
# 2. (2,2,3) 변경 c
# 3. (4,3) ndarray 생성 b
# 4. a,b를 row / column 기준으로 합치기
# 5. 슬라이싱
# 6. 행만 역순으로, 열만 역순으로, 전체 역순으로

##4. 불 인덱싱

In [151]:
import numpy as np
a=np.array([0,1, 2, 3, 4, 5, 6])
print(a)

[0 1 2 3 4 5 6]


In [152]:
print(a>2)

[False False False  True  True  True  True]


In [150]:
print(a[a>2])

[3 4 5 6]


##5. 조건 필터

In [173]:
a=np.array([0,1, 2, 3, 4, 5, 6])
result=a>2
result

array([False, False, False,  True,  True,  True,  True])

In [174]:
a[a>2]

array([3, 4, 5, 6])

In [175]:
a[a!=3]

array([0, 1, 2, 4, 5, 6])

In [176]:
print(a[(a>2) & (a<6)]) # 2보다 크고 6보다 작은 요소만 추출
print(a[a % 2==0]) # 2로 나눈 나머지가 0인 요소만 추출
print(a[a<a.mean( )]) # 평균보다 작은 값만 추출

[3 4 5]
[0 2 4 6]
[0 1 2]


In [177]:
print(a[True])  #[True,True,True,True,True,True]
print(a[False]) #[False,False,False,False,False,False]

[[0 1 2 3 4 5 6]]
[]


In [178]:
#1, 0~100 사이의 임의의 숫자 20개를 만들어서 출력하고 그중에 3 5 7의 배수만 출력
# np.random.seed(10)
a=np.random.randint(0, 100, 20)
print(a)
condition = (a % 3 == 0) | (a % 5 == 0) | (a % 7 == 0)
print(a[condition])
#2, 특정범위의 값 선택  25<= x <=50
condition = (25<= a) & (a <=50)
print(a[condition])

[28 30 89 25 78 81 85 62 13 41 33  4 87 94 28 39 91  9  7 22]
[28 30 25 78 81 85 33 87 28 39 91  9  7]
[28 30 25 41 33 28 39]


In [192]:
#질문
# 논리 연산에서 and 와 or는 좌우 피 연산자가 단일값
#  Ex  True and Fals
# &  |  는 리스트형식의 true false를 각각 1:1로 연산
import random
a = np.array([random.randint(0,100) for i in range(20)])
# print(a)
# print(a % 3 == 0)
# print(a % 5 == 0)
np.any(a % 3 == 0),  np.all(a % 3 == 0), (a % 3 == 0).any(), (a % 3 == 0).all()

# print(a[(a % 3 == 0) or (a % 5 == 0) or (a % 7 == 0)])
# print(a[(a % 3 == 0) | (a % 5 == 0) | (a % 7 == 0)])  # 가능
# print(a[a>a.mean()])


(True, False, True, False)

In [208]:
# axis는 행 렬 을 나타내는데.. axis가 적용된 함수는 우리가 생각하는 행 렬 의 반대 즉동작일때는 반대
# axis=(1,2)

# 2차원 배열에서 0이 하나라도  있으면  True
temp = np.random.randint(0, 10, 20).reshape(4, 5)
print(temp == 0)
(temp == 0).any()
# 행 렬 별로 any를 할수 있다. axis=0 행별로  vstack  row_stack
print( (temp == 0).any(axis=0) )
print( (temp == 0).any(axis=1) )  # 열별로 hstack.. column_stack

[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]
[False False False False False]
[False False False False]


In [199]:
test1 = np.array([True,False])
test2 = np.array([True,True])
print(True and False)
print(test1 & test2)

False
[ True False]


#Section 04. 넘파이 배열의 정렬
##1 기본 정렬: sort 함수

In [ ]:
a=np.array([2, 8, 9, 7, 3, 1, 4, 5, 6])
print(a, a.shape)
r=np.sort(a) # 원본 변경 없이 오름차순 정렬
print(r, a)

[2 8 9 7 3 1 4 5 6] (9,)
[1 2 3 4 5 6 7 8 9] [2 8 9 7 3 1 4 5 6]


In [ ]:
# 오름차순 정렬
a.sort()
print(a)

[1 2 3 4 5 6 7 8 9]


In [ ]:
# 내림차순 정렬
r=np.sort(a)[::-1]
print(r)

[9 8 7 6 5 4 3 2 1]


##2. 인덱스 반환 정렬: argsort 함수

In [ ]:
a=np.array([2, 8, 9, 7, 3, 1, 4, 5, 6])
print(a, a.shape)

[2 8 9 7 3 1 4 5 6] (9,)


In [ ]:
np.argsort(a)

array([5, 0, 4, 6, 7, 8, 3, 1, 2], dtype=int64)

In [ ]:
sort_index=np.argsort(a)
print(sort_index)

[5 0 4 6 7 8 3 1 2]


##3. 2차원 배열의 정렬

In [ ]:
arr2d=np.array([[5, 6, 7, 8],
 [4, 3, 2, 1],
 [10, 9, 12, 11]])
print(arr2d)
print(arr2d.shape)

[[ 5  6  7  8]
 [ 4  3  2  1]
 [10  9 12 11]]
(3, 4)


In [ ]:
# 열 방향으로 같은 행의 요소 정렬
np.sort(arr2d, axis=1)

array([[ 5,  6,  7,  8],
       [ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [ ]:
# 행 방향으로 같은 열의 요소 정렬
np.sort(arr2d, axis=0)

array([[ 4,  3,  2,  1],
       [ 5,  6,  7,  8],
       [10,  9, 12, 11]])

In [ ]:
# 열 방향으로 같은 행 정렬
print(arr2d)
print(np.sort(arr2d))
np.argsort(arr2d, axis=1)

[[ 5  6  7  8]
 [ 4  3  2  1]
 [10  9 12 11]]
[[ 5  6  7  8]
 [ 1  2  3  4]
 [ 9 10 11 12]]


array([[0, 1, 2, 3],
       [3, 2, 1, 0],
       [1, 0, 3, 2]], dtype=int64)

In [ ]:
# 행 방향으로 같은 열 정렬
print(arr2d)
print(np.sort(arr2d, axis=0))
np.argsort(arr2d, axis=0)

[[ 5  6  7  8]
 [ 4  3  2  1]
 [10  9 12 11]]
[[ 4  3  2  1]
 [ 5  6  7  8]
 [10  9 12 11]]


array([[1, 1, 1, 1],
       [0, 0, 0, 0],
       [2, 2, 2, 2]], dtype=int64)

#Section 05. 넘파이 배열의 연산
## 1. 넘파이 배열의 연산
### 배열 내 요소들의 연산

In [ ]:
# 같은 배열 내 요소의 합 구하기
import numpy as np
a=np.array([[1, 2, 3],
 [4, 5, 6]])
np.sum(a, axis=0), np.sum(a, axis=1)

(array([5, 7, 9]), array([ 6, 15]))

In [ ]:
a.sum()

21

###배열과 상수의 사칙연산

In [ ]:
a=np.array([[1, 2, 3],
 [4, 5, 6]])
b=2
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[3 4 5]
 [6 7 8]]
[[-1  0  1]
 [ 2  3  4]]
[[ 2  4  6]
 [ 8 10 12]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]]


In [ ]:
A=np.arange(1, 13).reshape(3, 4)
print(A+10)
print(A-10)
print(A*10)
print(A/10)

[[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]]
[[-9 -8 -7 -6]
 [-5 -4 -3 -2]
 [-1  0  1  2]]
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
[[0.1 0.2 0.3 0.4]
 [0.5 0.6 0.7 0.8]
 [0.9 1.  1.1 1.2]]


In [ ]:
A=np.arange(1, 13).reshape(3, 4)
A-1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### 배열과 배열의 요소 간 연산

In [ ]:
a=np.array([[1, 2, 3],
 [4, 5, 6]])
b=np.array([1, 2, 3]) # b=np.array([[1, 2, 3]])도 가능
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[2 4 6]
 [5 7 9]]
[[0 0 0]
 [3 3 3]]
[[ 1  4  9]
 [ 4 10 18]]
[[1.  1.  1. ]
 [4.  2.5 2. ]]


###배열 간의 곱셈과 행렬 곱셈의 차이

In [ ]:
a=np.array([[1, 2],
 [3, 4]])
b=np.array([[1, 2],
 [1, 2]])
print(a*b)
print(a.dot(b))

[[1 4]
 [3 8]]
[[ 3  6]
 [ 7 14]]


##2. 브로드캐스팅

In [ ]:
A=np.array([[1, 2],
 [3, 4]])
B=np.array([1, 2])
A+B

array([[2, 4],
       [4, 6]])

In [ ]:
A=np.array([[1, 2, 3],
 [4, 5, 6]])
B=np.array([2])
A+B

array([[3, 4, 5],
       [6, 7, 8]])

In [ ]:
A=np.array([[1, 2, 3],
 [4, 5, 6]])
B=np.array([[2],
 [4]])
A+B

array([[ 3,  4,  5],
       [ 8,  9, 10]])